version: '3.8'

services:
    redis:
      image: redis:6.2.6
    backend:
      build: ./example-backend
      ports:
        - 8080:8080
      environment:
        - REDIS_HOST=redis
    frontend:
      build: ./example-frontend
      ports:
        - 5000:5000
