version: '3.8'

services:
    nginx:
      image: nginx
      volumes:
        - ./nginx.conf:/etc/nginx/nginx.conf:ro
      ports:
        - 80:80
    db:
      image: postgres
      restart: unless-stopped
      environment:
        - POSTGRES_PASSWORD=secret
    redis:
      image: redis:6.2.6
    backend:
      build: ./example-backend
      ports:
        - 8080:8080
      environment:
        - REDIS_HOST=redis
        - POSTGRES_HOST=db
        - POSTGRES_PASSWORD=secret
    frontend:
      build: ./example-frontend
      ports:
        - 5000:5000
