version: "3.8"

services:
    backend:
      build: ./ml-kurkkumopo-backend
      ports:
        - 5000:5000
      volumes:
        - model:/src/model
    frontend:
      build: ./ml-kurkkumopo-frontend
      ports:
        - 3000:3000
    training:
      build: ./ml-kurkkumopo-training
      volumes:
        - model:/src/model
        - imgs:/src/imgs
        - data:/src/data

volumes:
  model:
  imgs:
  data:
